# Generated by Django 5.1.6 on 2025-02-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20250221_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('UAH', 'Ukrainian Hryvnia')], default='UAH', max_length=3),
        ),
    ]
