# Generated by Django 5.1.6 on 2025-02-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_table_currency_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(related_name='transactions', to='finances.category'),
        ),
    ]
